version: '3'

services:
  reverse-proxy:
    image: nginx
    container_name: reverse-proxy
    depends_on:
      - service1
      - service2
    volumes:
      - ./nginx_practice/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_practice/index.html:/etc/nginx/html/index.html
    ports:
      - 80:80

  service1:
    image: fastapi-practice
    container_name: service1
    build:
      context: ./fastapi_practice
    ports:
      - 8888:80
  
  service2:
    image: fastapi-practice
    container_name: service2
    build:
      context: ./fastapi_practice
    ports:
      - 8889:80


